module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V3.Audio
import Evergreen.V3.Midi
import Evergreen.V3.Types
import Evergreen.V5.Audio
import Evergreen.V5.Midi
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Result


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V5.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Audio_Model migrate_Types_FrontendMsg_ migrate_Types_FrontendModel_


migrate_Audio_Audio : Evergreen.V3.Audio.Audio -> Evergreen.V5.Audio.Audio
migrate_Audio_Audio old =
    case old of
        Evergreen.V3.Audio.Group p0 ->
            Evergreen.V5.Audio.Group (p0 |> List.map migrate_Audio_Audio)

        Evergreen.V3.Audio.BasicAudio p0 ->
            Evergreen.V5.Audio.BasicAudio
                { source = p0.source |> migrate_Audio_Source
                , startTime = p0.startTime
                , settings = p0.settings |> migrate_Audio_PlayAudioConfig
                }

        Evergreen.V3.Audio.Effect p0 ->
            Evergreen.V5.Audio.Effect
                { effectType = p0.effectType |> migrate_Audio_EffectType
                , audio = p0.audio |> migrate_Audio_Audio
                }


migrate_Audio_AudioLoadRequest_ : (userMsg_old -> userMsg_new) -> Evergreen.V3.Audio.AudioLoadRequest_ userMsg_old -> Evergreen.V5.Audio.AudioLoadRequest_ userMsg_new
migrate_Audio_AudioLoadRequest_ migrate_userMsg old =
    { userMsg = old.userMsg |> migrate_List_Nonempty_Nonempty (Tuple.mapBoth (Result.mapError migrate_Audio_LoadError >> Result.map migrate_Audio_Source) migrate_userMsg)
    , audioUrl = old.audioUrl
    }


migrate_Audio_BufferId : Evergreen.V3.Audio.BufferId -> Evergreen.V5.Audio.BufferId
migrate_Audio_BufferId old =
    case old of
        Evergreen.V3.Audio.BufferId p0 ->
            Evergreen.V5.Audio.BufferId p0


migrate_Audio_EffectType : Evergreen.V3.Audio.EffectType -> Evergreen.V5.Audio.EffectType
migrate_Audio_EffectType old =
    case old of
        Evergreen.V3.Audio.ScaleVolume p0 ->
            Evergreen.V5.Audio.ScaleVolume p0

        Evergreen.V3.Audio.ScaleVolumeAt p0 ->
            Evergreen.V5.Audio.ScaleVolumeAt p0

        Evergreen.V3.Audio.Offset p0 ->
            Evergreen.V5.Audio.Offset p0


migrate_Audio_FlattenedAudio : Evergreen.V3.Audio.FlattenedAudio -> Evergreen.V5.Audio.FlattenedAudio
migrate_Audio_FlattenedAudio old =
    { source = old.source |> migrate_Audio_Source
    , startTime = old.startTime
    , startAt = old.startAt
    , offset = old.offset
    , volume = old.volume
    , volumeTimelines = old.volumeTimelines
    , loop = old.loop
    , playbackRate = old.playbackRate
    }


migrate_Audio_LoadError : Evergreen.V3.Audio.LoadError -> Evergreen.V5.Audio.LoadError
migrate_Audio_LoadError old =
    case old of
        Evergreen.V3.Audio.FailedToDecode ->
            Evergreen.V5.Audio.FailedToDecode

        Evergreen.V3.Audio.NetworkError ->
            Evergreen.V5.Audio.NetworkError

        Evergreen.V3.Audio.UnknownError ->
            Evergreen.V5.Audio.UnknownError

        Evergreen.V3.Audio.ErrorThatHappensWhenYouLoadMoreThan1000SoundsDueToHackyWorkAroundToMakeThisPackageBehaveMoreLikeAnEffectPackage ->
            Evergreen.V5.Audio.ErrorThatHappensWhenYouLoadMoreThan1000SoundsDueToHackyWorkAroundToMakeThisPackageBehaveMoreLikeAnEffectPackage


migrate_Audio_Model : (userMsg_old -> userMsg_new) -> (userModel_old -> userModel_new) -> Evergreen.V3.Audio.Model userMsg_old userModel_old -> Evergreen.V5.Audio.Model userMsg_new userModel_new
migrate_Audio_Model migrate_userMsg migrate_userModel old =
    case old of
        Evergreen.V3.Audio.Model p0 ->
            Evergreen.V5.Audio.Model (p0 |> migrate_Audio_Model_ migrate_userMsg migrate_userModel)


migrate_Audio_Model_ : (userMsg_old -> userMsg_new) -> (userModel_old -> userModel_new) -> Evergreen.V3.Audio.Model_ userMsg_old userModel_old -> Evergreen.V5.Audio.Model_ userMsg_new userModel_new
migrate_Audio_Model_ migrate_userMsg migrate_userModel old =
    { audioState = old.audioState |> Dict.map (\k -> migrate_Audio_FlattenedAudio)
    , nodeGroupIdCounter = old.nodeGroupIdCounter
    , userModel = old.userModel |> migrate_userModel
    , requestCount = old.requestCount
    , pendingRequests = old.pendingRequests |> Dict.map (\k -> migrate_Audio_AudioLoadRequest_ migrate_userMsg)
    , samplesPerSecond = old.samplesPerSecond
    , sourceData = old.sourceData
    , lastAudio = old.lastAudio |> migrate_Audio_Audio
    }


migrate_Audio_PlayAudioConfig : Evergreen.V3.Audio.PlayAudioConfig -> Evergreen.V5.Audio.PlayAudioConfig
migrate_Audio_PlayAudioConfig old =
    old


migrate_Audio_Source : Evergreen.V3.Audio.Source -> Evergreen.V5.Audio.Source
migrate_Audio_Source old =
    case old of
        Evergreen.V3.Audio.File p0 ->
            Evergreen.V5.Audio.File
                { bufferId = p0.bufferId |> migrate_Audio_BufferId
                }


migrate_List_Nonempty_Nonempty : (a_old -> a_new) -> List.Nonempty.Nonempty a_old -> List.Nonempty.Nonempty a_new
migrate_List_Nonempty_Nonempty migrate_a old =
    old |> List.Nonempty.map migrate_a


migrate_Midi_MidiEvent : Evergreen.V3.Midi.MidiEvent -> Evergreen.V5.Midi.MidiEvent
migrate_Midi_MidiEvent old =
    case old of
        Evergreen.V3.Midi.SequenceNumber p0 ->
            Evergreen.V5.Midi.SequenceNumber p0

        Evergreen.V3.Midi.Text p0 ->
            Evergreen.V5.Midi.Text p0

        Evergreen.V3.Midi.Copyright p0 ->
            Evergreen.V5.Midi.Copyright p0

        Evergreen.V3.Midi.TrackName p0 ->
            Evergreen.V5.Midi.TrackName p0

        Evergreen.V3.Midi.InstrumentName p0 ->
            Evergreen.V5.Midi.InstrumentName p0

        Evergreen.V3.Midi.Lyrics p0 ->
            Evergreen.V5.Midi.Lyrics p0

        Evergreen.V3.Midi.Marker p0 ->
            Evergreen.V5.Midi.Marker p0

        Evergreen.V3.Midi.CuePoint p0 ->
            Evergreen.V5.Midi.CuePoint p0

        Evergreen.V3.Midi.ChannelPrefix p0 ->
            Evergreen.V5.Midi.ChannelPrefix p0

        Evergreen.V3.Midi.Tempo p0 ->
            Evergreen.V5.Midi.Tempo p0

        Evergreen.V3.Midi.SMPTEOffset p0 p1 p2 p3 p4 ->
            Evergreen.V5.Midi.SMPTEOffset p0 p1 p2 p3 p4

        Evergreen.V3.Midi.TimeSignature p0 p1 p2 p3 ->
            Evergreen.V5.Midi.TimeSignature p0 p1 p2 p3

        Evergreen.V3.Midi.KeySignature p0 p1 ->
            Evergreen.V5.Midi.KeySignature p0 p1

        Evergreen.V3.Midi.SequencerSpecific p0 ->
            Evergreen.V5.Midi.SequencerSpecific p0

        Evergreen.V3.Midi.SysEx p0 p1 ->
            Evergreen.V5.Midi.SysEx (p0 |> migrate_Midi_SysExFlavour) p1

        Evergreen.V3.Midi.Unspecified p0 p1 ->
            Evergreen.V5.Midi.Unspecified p0 p1

        Evergreen.V3.Midi.NoteOn p0 p1 p2 ->
            Evergreen.V5.Midi.NoteOn p0 p1 p2

        Evergreen.V3.Midi.NoteOff p0 p1 p2 ->
            Evergreen.V5.Midi.NoteOff p0 p1 p2

        Evergreen.V3.Midi.NoteAfterTouch p0 p1 p2 ->
            Evergreen.V5.Midi.NoteAfterTouch p0 p1 p2

        Evergreen.V3.Midi.ControlChange p0 p1 p2 ->
            Evergreen.V5.Midi.ControlChange p0 p1 p2

        Evergreen.V3.Midi.ProgramChange p0 p1 ->
            Evergreen.V5.Midi.ProgramChange p0 p1

        Evergreen.V3.Midi.ChannelAfterTouch p0 p1 ->
            Evergreen.V5.Midi.ChannelAfterTouch p0 p1

        Evergreen.V3.Midi.PitchBend p0 p1 ->
            Evergreen.V5.Midi.PitchBend p0 p1


migrate_Midi_MidiMessage : Evergreen.V3.Midi.MidiMessage -> Evergreen.V5.Midi.MidiMessage
migrate_Midi_MidiMessage old =
    old |> Tuple.mapSecond migrate_Midi_MidiEvent


migrate_Midi_MidiRecording : Evergreen.V3.Midi.MidiRecording -> Evergreen.V5.Midi.MidiRecording
migrate_Midi_MidiRecording old =
    case old of
        Evergreen.V3.Midi.SingleTrack p0 p1 ->
            Evergreen.V5.Midi.SingleTrack p0 (p1 |> migrate_Midi_Track)

        Evergreen.V3.Midi.MultipleTracks p0 p1 p2 ->
            Evergreen.V5.Midi.MultipleTracks (p0 |> migrate_Midi_TracksType)
                p1
                (p2 |> List.map migrate_Midi_Track)


migrate_Midi_SysExFlavour : Evergreen.V3.Midi.SysExFlavour -> Evergreen.V5.Midi.SysExFlavour
migrate_Midi_SysExFlavour old =
    case old of
        Evergreen.V3.Midi.F0 ->
            Evergreen.V5.Midi.F0

        Evergreen.V3.Midi.F7 ->
            Evergreen.V5.Midi.F7


migrate_Midi_Track : Evergreen.V3.Midi.Track -> Evergreen.V5.Midi.Track
migrate_Midi_Track old =
    old |> List.map migrate_Midi_MidiMessage


migrate_Midi_TracksType : Evergreen.V3.Midi.TracksType -> Evergreen.V5.Midi.TracksType
migrate_Midi_TracksType old =
    case old of
        Evergreen.V3.Midi.Simultaneous ->
            Evergreen.V5.Midi.Simultaneous

        Evergreen.V3.Midi.Independent ->
            Evergreen.V5.Midi.Independent


migrate_Types_FrontendModel_ : Evergreen.V3.Types.FrontendModel_ -> Evergreen.V5.Types.FrontendModel_
migrate_Types_FrontendModel_ old =
    { key = old.key
    , source = old.source |> migrate_Types_Source
    , recording = old.recording |> Result.map migrate_Midi_MidiRecording
    , pianoSamples = old.pianoSamples |> Dict.map (\k -> Result.mapError migrate_Audio_LoadError >> Result.map migrate_Audio_Source)
    , playbackStart = old.playbackStart
    , now = old.now
    , dummyField = 123
    }


migrate_Types_FrontendMsg_ : Evergreen.V3.Types.FrontendMsg_ -> Evergreen.V5.Types.FrontendMsg_
migrate_Types_FrontendMsg_ old =
    case old of
        Evergreen.V3.Types.UrlClicked p0 ->
            Evergreen.V5.Types.UrlClicked p0

        Evergreen.V3.Types.UrlChanged p0 ->
            Evergreen.V5.Types.UrlChanged p0

        Evergreen.V3.Types.MidiFileRequested ->
            Evergreen.V5.Types.MidiFileRequested

        Evergreen.V3.Types.MidiFileSelected p0 ->
            Evergreen.V5.Types.MidiFileSelected p0

        Evergreen.V3.Types.MidiFileLoaded p0 p1 ->
            Evergreen.V5.Types.MidiFileLoaded p0 p1

        Evergreen.V3.Types.PianoSampleLoaded p0 p1 ->
            Evergreen.V5.Types.PianoSampleLoaded p0
                (p1 |> Result.mapError migrate_Audio_LoadError >> Result.map migrate_Audio_Source)

        Evergreen.V3.Types.PressedPlay ->
            Evergreen.V5.Types.PressedPlay

        Evergreen.V3.Types.GotPlaybackStartTime p0 ->
            Evergreen.V5.Types.GotPlaybackStartTime p0

        Evergreen.V3.Types.PressedStop ->
            Evergreen.V5.Types.PressedStop

        Evergreen.V3.Types.Tick p0 ->
            Evergreen.V5.Types.Tick p0

        Evergreen.V3.Types.NoOp ->
            Evergreen.V5.Types.NoOp


migrate_Types_Source : Evergreen.V3.Types.Source -> Evergreen.V5.Types.Source
migrate_Types_Source old =
    case old of
        Evergreen.V3.Types.Demo ->
            Evergreen.V5.Types.Demo

        Evergreen.V3.Types.FromFile p0 ->
            Evergreen.V5.Types.FromFile p0
